// Generated by scripts/export-abi.mjs from contracts/out/X429Queue.sol/X429Queue.json. Do not edit.
export const x429Abi = [
  {
    "type": "function",
    "name": "MAX_PASS_PER_TX",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_QUEUE_LENGTH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimable",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createQueue",
    "inputs": [
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "maxLength",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "meta",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getQueue",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "offset",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "limit",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "list",
        "type": "tuple[]",
        "internalType": "struct X429Queue.TicketView[]",
        "components": [
          {
            "name": "id",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "skipPrice",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "joinedAt",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "timesPassed",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "earned",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "paid",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "join",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "skipPrice",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "outputs": [
      {
        "name": "ticketId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "joinAndOvertake",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "skipPrice",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "maxPositions",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "ticketId",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "passed",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "paid",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "kick",
    "inputs": [
      {
        "name": "ticketId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "leave",
    "inputs": [
      {
        "name": "ticketId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "overtake",
    "inputs": [
      {
        "name": "ticketId",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "maxPositions",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "passed",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "paid",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "positionOf",
    "inputs": [
      {
        "name": "ticketId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "position",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "queueCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "queueInfo",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct X429Queue.Queue",
        "components": [
          {
            "name": "operator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "length",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxLength",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "overtakes",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "head",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "tail",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "joined",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "served",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "totalCompensation",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "meta",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quote",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "ticketId",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "maxPositions",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "budget",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "passed",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "cost",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "serve",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "count",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "servedCount",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOperator",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSkipPrice",
    "inputs": [
      {
        "name": "ticketId",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "skipPrice",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ticketCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tickets",
    "inputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "queueId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum X429Queue.Status"
      },
      {
        "name": "timesPassed",
        "type": "uint24",
        "internalType": "uint24"
      },
      {
        "name": "joinedAt",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "prev",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "next",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "skipPrice",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "earned",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "paid",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "withdrawFor",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Joined",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "ticketId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "skipPrice",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "position",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Left",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "ticketId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "kicked",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OperatorChanged",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Overtook",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "ticketId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "positions",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "paid",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Passed",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "passedTicketId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "passedOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "byTicketId",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "amount",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "QueueCreated",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "maxLength",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "meta",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Served",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "ticketId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "waited",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "timesPassed",
        "type": "uint24",
        "indexed": false,
        "internalType": "uint24"
      },
      {
        "name": "earned",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "paid",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SkipPriceSet",
    "inputs": [
      {
        "name": "queueId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "ticketId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "skipPrice",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "caller",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "InvalidMaxLength",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidOperator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidPositions",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOperator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotTicketOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotWaiting",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingPassed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingToWithdraw",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QueueFull",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Reentrancy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownQueue",
    "inputs": []
  }
] as const;
