[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 64
fail_on_revert = false

[rpc_endpoints]
arc = "https://rpc.mainnet.arc.io"
anvil = "http://127.0.0.1:8545"
