#!/usr/bin/env node
// Writes sdk/src/abi.ts from the Foundry artifact. Run `forge build` in contracts/ first.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = join(root, "contracts/out/X429Queue.sol/X429Queue.json");
const target = join(root, "sdk/src/abi.ts");

const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
if (!Array.isArray(abi) || abi.length === 0) throw new Error(`no ABI in ${artifact}`);

const body = JSON.stringify(abi, null, 2);
mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  `// Generated by scripts/export-abi.mjs from contracts/out/X429Queue.sol/X429Queue.json. Do not edit.\n` +
    `export const x429Abi = ${body} as const;\n`,
);
console.log(`wrote ${target} (${abi.length} entries)`);
